baseURL: https://itscd.xyz
languageCode: en-us
title: Miguel Diaz

params:
  defaultTheme: dark
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  homeInfoParams:
    Content: Backend developer that works on blockchain rather frequently

  socialIcons:
    - name: "github"
      url: "https://github.com/aguxez"
